### ISSUE TITLE
[BUG] 기존에 회원가입된 이메일로 회원가입 시, 에러 발생

### ISSUE THREAD

**Issue by GBGreenBravo** [Kernel360/E2E1-TeachMe#171]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
기존에 회원가입된 이메일로 회원가입 시, 에러페이지 응답

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 회원가입하고 바로 비밀번호를 까먹어서, 이전에 회원가입한 이메일로 다시 회원가입을 시도 했습니다.
2. 500에러 발생

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
"기존에 존재하는 회원입니다"와 같은 메세지를 띄워주시면 좋을 것 같습니다!

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
<img width="1439" alt="image" src="https://github.com/Kernel360/E2E1-TeachMe/assets/147565215/11165337-d83b-427c-9c69-5a0e449c7997">

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 내일부터 확인 가능하십니다 :) 감사합니다
