### ISSUE TITLE
[BUG] 가나다 순 정렬 시, 이슈 있는 것 같아요

### ISSUE THREAD

**Issue by linglong67** [Kernel360/E2E1-TeachMe#172]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
가나다 순 정렬했는데 초격차 로 시작하는 강의가 2번째로 올라옵니다.

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 강의 리스트 페이지 클릭
2. '자막이 있어서 입문하기 쉬운 오토캐드 2023' 강의 상세정보 클릭
3. 리뷰 작성 시 404에러 발생 (로그인 안함)

강의 리스트 조회했습니다

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
ㅊ 으로 시작하는 강의는 첫 페이지에 안 나올 줄 알았어요

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
<img width="1211" alt="image" src="https://github.com/Kernel360/E2E1-TeachMe/assets/88479739/a3b47050-98fc-4498-a595-0ecfb6741820">

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)
UI가 훌륭합니다~ 테스트할 때 눈에 잘 들어와요

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 내일부터 확인 가능하십니다 :) 감사합니다
