### ISSUE TITLE
[BUG] 긴 아이디에 대한 validation이 되지 않음

### ISSUE THREAD

**Issue by HyunJunSon** [Kernel360/E2E1-TeachMe#173]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
아이디를 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

요렇게 입력하니까, validation이 되지 않고, error 페이지로 넘어가는 심각한 오류가 있습니다. 강력하게 시정을 요청합니다.

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
순수하게 나는 저 아이디를 하고 싶습니다. 

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
가입이 안되어야 합니다.
**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
![image](https://github.com/Kernel360/E2E1-TeachMe/assets/91066575/3f429ae1-fba5-4a1c-b4b2-4df14ac8238a)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
해당 부분 확인 후 조치하겠습니다 ID는 DB제한에 맞춰 제한하도록 하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
