### ISSUE TITLE
[BUG] 1시간 미만 강의 시간 표시가 안 되요

### ISSUE THREAD

**Issue by linglong67** [Kernel360/E2E1-TeachMe#174]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
강의 시간이 비어있는 경우가 있어요 

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 강의 리스트 페이지 클릭
2. '자막이 있어서 입문하기 쉬운 오토캐드 2023' 강의 상세정보 클릭
3. 리뷰 작성 시 404에러 발생 (로그인 안함)

리스트 조회할 때, 강의 시간 없는 데이터가 보입니다.

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
시간 나와야되지 않을까요?
분량이 1시간 미만인 강의는 안나오는 것 같긴 한데 수정해주시면 좋을 것 같아요 

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
<img width="1161" alt="image" src="https://github.com/Kernel360/E2E1-TeachMe/assets/88479739/03f0c57a-3c7a-440b-a8c8-9a9f4cb2a9d8">

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
