### ISSUE TITLE
[BUG] 회원가입 버튼을 눌러도 이동 되지 않아요

### ISSUE THREAD

**Issue by Hju95** [Kernel360/E2E1-TeachMe#176]
**버그 설명**
아이디, 비밀번호 자동으로 들어간 상태에서 회원가입이 누를  시 회원가입 페이지로 넘어가지 않아요

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 아이디, 비밀번호 자동으로 들어간 상태
2. 회원가입 버튼 누름

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
회원가입 페이지로 이동

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
<img width="564" alt="image" src="https://github.com/Kernel360/E2E1-TeachMe/assets/59231743/7ae6045c-bb28-4489-a29b-498f20888a76">

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
