### ISSUE TITLE
[BUG] 통계에 강의명이 길 때 뒷부분이 ... 으로 나와서 정확한 강의 확인이 안되요

### ISSUE THREAD

**Issue by linglong67** [Kernel360/E2E1-TeachMe#177]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
제목과 동일합니다

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 강의 리스트 페이지 클릭
2. '자막이 있어서 입문하기 쉬운 오토캐드 2023' 강의 상세정보 클릭
3. 리뷰 작성 시 404에러 발생 (로그인 안함)

통계페이지에서 데이터를 보다가 발견했습니다

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
그래프 내 데이터 hover 시 데이터를 보여줄 수 없다면, 그래프 하단에 나온 강의명에 마우스 가져다놓을 때라도 강의명 다 보여야 강의 확인 가능할 것 같아요

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
<img width="962" alt="image" src="https://github.com/Kernel360/E2E1-TeachMe/assets/88479739/9a60b5ad-5bf7-4c90-af2a-5ca003bf1f22">

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
강의명이 대부분 길이가 길기 때문에, 모든 제목을 표시하면 그래프가 이름에 가려 보이지않고 깨지는 현상이 발생했답니다...
해당 부분은 강의의 Id를 제목 앞에 표시하는 방향으로 수정하여, 제목 전부를 확인하지 않아도 강의를 구분하여 확인할 수 있도록 개선하겠습니다.
(조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
