### ISSUE TITLE
[BUG] 리뷰를 남길수 있는 글자수의 제한이 없습니다. 제한을 둡시다. 아니면 도르마무가 또 찾아옵니다.

### ISSUE THREAD

**Issue by HyunJunSon** [Kernel360/E2E1-TeachMe#178]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
리뷰를 계속 남길수 있습니다. 당신의 디비가 위험합니다.
**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
리뷰를 좀 길게 남겼습니다.

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
댓글 작성 글자수가 제한이 되길 기대했습니다.
**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
![image](https://github.com/Kernel360/E2E1-TeachMe/assets/91066575/c6d89a3c-710a-456a-88e6-2abe1d8ef821)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)
사랑합니다. 티치미 쓰고 싶어요. 상용화 해주세요.

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

도르마무.. 그만 찾아와 주세요

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
