### ISSUE TITLE
[BUG] 회원 가입 오류

### ISSUE THREAD

**Issue by oxix97** [Kernel360/E2E1-TeachMe#179]
**버그 설명**
회원 가입 상황 500 error
**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 회원 가입 클릭시 500 white label error

입력값
oxix
oxix
!qwer1234
!qwer1234

**정상 동작**
로그인 화면 혹은 로그인된 화면으로 이동하는 것으로 알고 있었습니다.

**스크린샷**

![스크린샷 2023-11-22 오전 11 59 25](https://github.com/Kernel360/E2E1-TeachMe/assets/72330632/b034ccdc-9442-42e2-bbe0-ecde35c2e3c0)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
해당 부분은 이미 가입된 계정이 있는데 또 가입 요청이 서버에 전달되어서 발생하는 오류였습니다.
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
