### ISSUE TITLE
[BUG] 댓글 수정 버튼을 누르면 기존 댓글이 전부 날아가고 , 빈화면이 나옵니다. 이전 댓글을 보고 싶어서, 뒤로가기를 하면, 엉뚱한 페이지 나옴

### ISSUE THREAD

**Issue by HyunJunSon** [Kernel360/E2E1-TeachMe#180]
**버그 설명**
댓글 수정 버튼을 누르면 기존 댓글이 전부 날아가고 , 빈화면이 나옵니다. 이전 댓글을 보고 싶어서, 뒤로가기를 하면, 엉뚱한 페이지 나옴

**발생 경위**
제가 쓴 도르마무 댓글을 수정하고 싶어서 수정 버튼을 눌렀는데, 위와 같은 현상 발생

**정상 동작**
기존 댓글 데이터가 나오고, 수정을 할수 있게 되길
**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
![image](https://github.com/Kernel360/E2E1-TeachMe/assets/91066575/d15b9494-e59b-4144-ae83-a4b24e942aad)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
한 페이지에서 수정작업이 이루어지기 때문에 나타나는 현상입니다.
리뷰 작성중 취소하여 이전으로 돌아가는 기능을 만들도록 하겠습니다. 감사합니다.
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
