### ISSUE TITLE
[BUG] 회원 가입 시 아이디 한글로 가능 / 댓글 페이지 전부 보이게 해주세요

### ISSUE THREAD

**Issue by fingersdanny** [Kernel360/E2E1-TeachMe#181]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
> 원래 아이디를 한글로 가입이 되게끔 하신걸까요? 현재는 한글로 회원가입이 됩니다.
> 댓글 페이지가 다 보이면 좋겠습니다 

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 강의 리스트 페이지 클릭
2. '자막이 있어서 입문하기 쉬운 오토캐드 2023' 강의 상세정보 클릭
3. 리뷰 작성 시 404에러 발생 (로그인 안함)

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
![image](https://github.com/Kernel360/E2E1-TeachMe/assets/54776553/697529fb-69b9-401a-a070-999fd774cf81)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)
고생하셨습니다~~~~~

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
아이디는 한글이 안되는쪽으로,,,, 조치해보겠습니다..
페이징은 너무 길어지면 비주얼이 별로라.... 추후에 lazy-load 형태로 개선해보고자 합니다. (드래그 할때마다 요청으로 불러오는 형태)
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
아이디는 영문 숫자 및 일부 특수문자로만 회원가입이 되도록 수정하였습니다.
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다
