### ISSUE TITLE
[BUG] 버그X; 바로가기 클릭 시 새탭 로드

### ISSUE THREAD

**Issue by GBGreenBravo** [Kernel360/E2E1-TeachMe#182]
**버그 설명**
(버그에 대한 설명을 명확하고 상세하게 작성해주세요)
버그는 아닙니다! 

**발생 경위**
(버그가 발생하게 된 경위를 아래 예시를 참고하여 설명해주세요)
1. 강의 상세 페이지에서 [홈페이지 바로가기]나 [인프런/패스트캠퍼스 바로가기] 클릭
2. 현재 탭이 TeachMe에서 인프런/패스트캠퍼스 사이트로 변경됨.

**정상 동작**
(기대했던 정상 동작은 무엇이었는지를 명확하고 상세하게 작성해주세요)
바로가기 클릭 시, 현재 탭에서 주소가 이동되도록 설정돼 있습니다. 
그런데 TeachMe의 탭이 인프런/패스트캠퍼스의 탭으로 바뀌게 되면, TeachMe에서 제공하는 검색/필터링 기능을 각 사이트에서도 제공하기에
인프런/패스트캠퍼스 모두 보고싶다는 점 빼고는 TeachMe 사이트로 돌아갈 요인이 적을 것 같다는 생각이 있습니다.
그래서 다른 사이트로 이동하는 [바로가기] 클릭 시, (가능하다면) 새탭에서 해당 링크를 띄우는 것이 더 낫지 않을까하는 사소한 의견이 있습니다!

**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by stoneHee99** [comment]
기여해주셔서 감사합니다!
새탭으로 뜨도록 수정하겠습니다.
해당 부분 확인 후 조치하겠습니다 (조치 후 의견 추가로 남기고 issue는 자동으로 close됩니다)

**Comment by stoneHee99** [comment]
수정완료되어 close 합니다. 늦어도 내일부터 확인 가능하십니다 :) 감사합니다

**Comment by GBGreenBravo** [comment]
새탭으로 띄우는 건 해본 적 없었는데, 코드 읽어보도록 하겠습니다! 적극적인 반영 감사합니다:)
